before_build:
- ps: nuget restore

image: Visual Studio 2017

platform:
  - x86

configuration:
  - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
  - path: TwitchChatVideo/bin/x86/Release/*
  - type: zip

deploy:
  provider: GitHub
  auth_token: "%ghreleases%"
  tag: "v$(appveyor_build_version)"
