before_build:
- ps: nuget restore

image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true

platform:
  - x86

configuration:
  - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

after_build:
  - 7z a TwitchChatVideo.zip %APPVEYOR_BUILD_FOLDER%/TwitchChatVideo/bin/x86/Release/*

artifacts:
  - path: TwitchChatVideo.zip

deploy:
  provider: GitHub
  auth_token: "%ghreleases%"
  tag: "v$(appveyor_build_version)"
